spring:
  application:
    name: lms
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    generate-ddl: true
    show-sql: true
#  security:
#    user:
#      name: 'zcy0052800@1'
#      password: 'zcy521'
  mail:
    host: localhost
    port: 1025

my:
  admin:
    admin-page-content-list:
      - name: 'dashboard'
        description: "dashboard's description"
        data : 'dont know'
      - name: 'users'
        description: "users's description"
        data: 'i dont know'
