spring:
  application:
    name: lms
  security:
    user:
      name: 'zcy0052800@1'
      password: 'zcy521'
my:
  admin:
    admin-page-content-list:
      - name: 'dashboard'
        description: "dashboard's description"
        data : 'dont know'
      - name: 'users'
        description: "users's description"
        data: 'i dont know'
